[package]
name = "redshift-rebooted"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5", features = ["derive"] }
x11rb = { version = "0.13", features = ["randr"] }
